-- SCHEMA: SMS_GATEWAY_USER

-- DROP SCHEMA IF EXISTS "SMS_GATEWAY_USER" ;

CREATE SCHEMA IF NOT EXISTS "SMS_GATEWAY_USER"
    AUTHORIZATION postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "SMS_GATEWAY_USER"
GRANT UPDATE, SELECT, INSERT ON TABLES TO pg_database_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "SMS_GATEWAY_USER"
GRANT ALL ON SEQUENCES TO pg_database_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "SMS_GATEWAY_USER"
GRANT EXECUTE ON FUNCTIONS TO pg_database_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "SMS_GATEWAY_USER"
GRANT USAGE ON TYPES TO pg_database_owner;